#default: &default
#  adapter: postgresql
#  pool: 5
#  timeout: 5000
#  host: localhost
#  username: auto_parts
#  password: polopolo
#
#development:
#  <<: *default
#  database: support_issue_traking_development
#
#test:
#  <<: *default
#  database: support_issue_traking_test

production:
  adapter: postgresql
  pool: 5
  encoding: UTF8
  timeout: 5000
  host: ec2-54-195-252-202.eu-west-1.compute.amazonaws.com
  username: xjjbitmplfevxd
  password: NALsthJItZwsyg8ztUyCqGuycT
  adapter: postgresql
  database: d8ig4rs2jsv3t6
