default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: auto_parts
  password: polopolo

development:
  <<: *default
  database: support_issue_traking_development

test:
  <<: *default
  database: support_issue_traking_test

production:
  adapter: postgresql
  encoding: utf8
  pool: 5
