#s Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc8babe095bccefee742264fc8e0942c41d102348c4704b052950f5c84654d7ad1f6f8d8c8630885aab0a5bf89d902f02e6dc7ba5992f25c3e884d36b493862c

test:
  secret_key_base: e91b4390f5f5db63ce220915655b8282cca080ffee65e9a042bf6a913c4ca72ba9cb5beb4bce1f10e281c457bc9bb925f94e643564dc68f894e2d059b15a134b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
